issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - lll
        - dupl

linters-settings:
  gocyclo:
    min-complexity: 35

  gocognit:
    min-complexity: 60

  lll:
    line-length: 140
    tab-width: 2

  misspell:
    ignore-words:
      - mosquitto

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

  # don't enable:
  # - funlen
  # - gochecknoglobals
  # - gochecknoinits
  # - golint for now, since code isn't fully commented yet
  # - godox
  # - gosec
  # - staticcheck
  # - unparam
