run:
  build-tags:
    - citest

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - const
        - dupl
        - gochecknoglobals
        - goconst
        - golint
        - unparam

linters-settings:
  gocyclo:
    min-complexity: 35

  gocognit:
    min-complexity: 60

  lll:
    line-length: 140
    tab-width: 2

  misspell:
    ignore-words:
      - mosquitto

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - structcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - unparam

  # don't enable:
  # - funlen
  # - godox
  # - gosec
